### ISSUE TITLE
No standard output for this job

### ISSUE THREAD

**Issue by JianguoRao** [icatproject/topcat_ijp_plugin#25]
After submitted the job and look at:

Job Details For Job 1233
page, got
There is no standard output for this job

It looks like something wrong with the communication between the ijp server and the worker nodes vm77.
Brian found there is a certificate issue next Morning, but other similar jobs running overnight had
standard output.

Causing: unidentified

**Comment by brianritchie1312** [comment]
The logs show that job 1233 changed status between Queued and Running and back again several times, from shortly after submission (17:00) until going to Running at 17:12. Then the next status change is at 22:58, when Torque (qstat) was no longer reporting the job, so the IJP set the status to Completed. I think this means that qstat was reporting the job as Running until then (but only because the IJP should have logged a change in status otherwise). I don't know why Torque would "lose" the job, but that seems to be what happened.

**Comment by brianritchie1312** [comment]
Closing this, as we have moved away from using Torque.
