### ISSUE TITLE
Update jobs list hanging for Dan

### ISSUE THREAD

**Issue by JianguoRao** [icatproject/topcat_ijp_plugin#7]
This is a certificate issue for people using the topcat_ijp_plugin the first time on a computer ( figure out by Brian )

**Comment by brianritchie1312** [comment]
This happens when the IJP server is on a different host to the server running topcat, and the IJP server has a self-signed certificate. On first use from a machine, when the user connects to the topcat server they are warned about that server's certificate (if it is self-signed) and allowed to add an exception; but no such warning (or offer to except/accept) is made for the IJP server - instead, the connection quietly fails. The My Jobs list is normally populated from the IJP server, but since the connection is failing, it remains empty. (It is not hanging, it is simply being set to an empty list on each refresh.)

A workaround is to visit the old GUI on the IJP server directly: the browser will then warn about the IJP server's self-signed certificate, and allow the user to add an exception for it. After this, My Jobs etc. in the new GUI should work properly.

This should not be an issue in production, as the production systems should have "proper" signed certificates. I am not aware of a solution for self-signed certificates.

**Comment by brianritchie1312** [comment]
Closing this, as we are "unlikely" to create a configuration (separate ICAT and IJP servers, with self-signed certificates) where this problem arises. Note however that the suggested workaround is no longer an option, as the old GUI has been disabled.
